name: Sync Fork

on:
  schedule:
    - cron: '*/60 1 * * *' 
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          owner: piejanssens
          base: master
          head: master
